// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVL231Dz3eM47WA32Vk2HR9zCpW2vJrCg',
    appId: '1:866664101272:web:30b94f6fcbcfff6f48a7ed',
    messagingSenderId: '866664101272',
    projectId: 'esg-post-app',
    authDomain: 'esg-post-app.firebaseapp.com',
    storageBucket: 'esg-post-app.firebasestorage.app',
    measurementId: 'G-ZR8V1TM8RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVpZ5XK1XRJTUfGwVExICa4Z_Z-aJdMA',
    appId: '1:866664101272:android:630a4e6fd64f2bdd48a7ed',
    messagingSenderId: '866664101272',
    projectId: 'esg-post-app',
    storageBucket: 'esg-post-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg3izOC-BDtLm4MNxjUSFjWwK_AlBMjzw',
    appId: '1:866664101272:ios:8ca443a1c2366db248a7ed',
    messagingSenderId: '866664101272',
    projectId: 'esg-post-app',
    storageBucket: 'esg-post-app.firebasestorage.app',
    iosBundleId: 'com.indianpost.esg.esgPostOffice',
  );
}
